ALTER TABLE users ADD COLUMN email VARCHAR(255);
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE stores ADD COLUMN slug VARCHAR(255);
ALTER TABLE stores ADD CONSTRAINT uk_users_slug UNIQUE (slug);