ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE stores ADD COLUMN slug VARCHAR(255) NOT NULL;
ALTER TABLE stores ADD CONSTRAINT uk_stores_slug UNIQUE (slug);